### ISSUE TITLE
Clean up suggestion for GMS2 version of this engine.

### ISSUE THREAD

**Issue by skysanc** [VectorSatyr/SonicGMS2#1]
I think you can use the find and replace all functionality of GMS2 so that you can delete 2 unnecessary scripts.

find all: action_kill_object
replace with: instance_destroy

&

find all: action_inherited
replace with: event_inherited

**Comment by VectorSatyr** [comment]
Thank you. This is already in progress, but there is a lot more to change before I will push another commit with this updated.
