### ISSUE TITLE
Adding one of the abilities from sonic cd into SonicForGms 1 and 2

### ISSUE THREAD

**Issue by Atekuro95** [VectorSatyr/SonicGMS2#5]
I think you can add the peel out ability for sonic, just like what the other people did in their engines like Flicky Engine, and Gmate.

**Comment by VectorSatyr** [comment]
Thank you for the suggestion, but I will probably not be adding this feature at this time.

**Comment by Bluecoreg** [comment]
@Atekuro95 Here you go [Sonic GMS](https://github.com/Bluecoreg/SonicGMS) [Sonic GMS 2](https://github.com/Bluecoreg/SonicGMS2)

Probably not as clean as VectorSatyr would have made it, but it should get the job done. If you want Zoom Tubes you'll have to make that yourself.

**Comment by VectorSatyr** [comment]
@Bluecoreg It appears your branches are missing the new animations and sprites for the peelout. The game crashes when loading either build as a result of the files' absense.

**Comment by Bluecoreg** [comment]
You're absolutely right! For some reason I had the project file included in the git ignore, woops! Pushing a fix now, thank you.

The GM:S 1 version should work fine. Did you get an error for that one?

**Comment by VectorSatyr** [comment]
The GM:S version works as expected. Thank you for asking.
